### ISSUE TITLE
Regression: all releases were removed

### ISSUE THREAD

**Issue by ahadas** [dev-drprasad/delete-tag-and-release#13]
Hello,
I've used the following code to remove the tag `nightly` and its release with v0.2.0:
```yaml
- name: Remove previous tag and release
  uses: dev-drprasad/delete-tag-and-release@v0.2.0
  with:
     delete_release: true
     tag_name: nightly
  env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
and it worked well - a single release associated with the tag `nightly` was removed.
However, after [upgrading to v0.2.1](https://github.com/mucommander/mucommander/commit/a31bc9ee63c9738df734877926265766f1229333), this code [removed all the releases that were published under my repository](https://github.com/mucommander/mucommander/actions/runs/3665962657/jobs/6197383036)...

**Comment by thadguidry** [comment]
@ahadas Thanks for letting us know!

@ppd Thoughts?  What would happen if `shouldDeleteDraftRelease` were `null`? It would be falsy (equivalent of `false`) and so the filter would not have filtered? Although it seems their run used with `delete_draft_release: false` ?

```
Run dev-drprasad/delete-tag-and-release@v0.2.1
  with:
    delete_release: true
    tag_name: nightly
    delete_draft_release: false
  env:
    GITHUB_TOKEN: ***
📕  given repo is "mucommander/mucommander"
🏷  given tag is "nightly"
🍻  found 23 releases to delete
👍🏼  all releases deleted successfully!
✅  tag "nightly" deleted successfully!
```

**Comment by wardellbagby** [comment]
I want to confirm the same happened to me with [this run.](https://github.com/wardellbagby/lyricistant/actions/runs/3667318093/jobs/6199791645)

Also, I definitely didn't _explicitly_ set `delete_draft_release` to false; my Workflow file simply omits it.

```yaml
      - name: 'Delete current nightly tag and release'
        uses: 'dev-drprasad/delete-tag-and-release/@431bd3dd0512ac0ae8813bd830ebfaf4188d2211'
        with:
          delete_release: true
          tag_name: 'latest'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
```

@ahadas I [reached out to GitHub support ](https://support.github.com/contact?tags=rr-restore)in hopes they could restore the releases. Not sure if that'll work or not but worth a shot?

**Comment by ahadas** [comment]
> @ahadas I [reached out to GitHub support ](https://support.github.com/contact?tags=rr-restore)in hopes they could restore the releases. Not sure if that'll work or not but worth a shot?

Thanks, I also reached out to GitHub support this way, we'll see.. worst case, I saw that I can retrieve the assets and release details from https://web.archive.org/ (it has a snapshot from May that includes my latest stable release)

**Comment by ahadas** [comment]
@thadguidry I got a response from GitHub support that deleted releases cannot be restored, I think v0.2.1 better be dropped until this issue is resolved..

**Comment by thadguidry** [comment]
@ahadas agree and so I have changed v0.2.1 to a prelease with v0.2.1-beta tag suffix.  Been busy over the weekend, but I want to get a testing repo setup to help with CI/CD testing of the Release API and which will help catch these edge cases in the future.  Hopefully I can work on that this week.

(Regarding restoration - I am thinking ... if you have the old commit SHA's - perhaps from a local repo copy - a tag is a type of ref `refs/tags/`, so `git log --tag` or whatever log options you need and then you can know which commits you had tags on (or locally open the `.git/packed-refs` file), you could make new tags against those commits using standard git commands then regenerate those deleted releases against the new tags using the Release API, or GitHub CLI, or perhaps with the GitHub web gui under Releases)

**Comment by wardellbagby** [comment]
Restoration, at least for Lyricistant, isn't that easy. The assets associated with a GitHub release are lost forever, and I had 84 releases. I've changed build systems 3 times in those years; it'd be quite difficult to set up a script to build my app for all of its supported platforms now.

That being said, while it's a huge lost, I can move forward from this. I just don't want this to happen to anyone else.

I think we should go a bit further than just tagging this as a pre-release. The GitHub Actions page with its huge "use latest version" still is prompting people to use v0.2.1-beta. Best to just revert the commit and delete the tag for now. You can add it back later once the testing is in place and the bug is fixed. Especially since people can reference a commit directly in an action instead of using a version.

**Comment by thadguidry** [comment]
@wardellbagby Indeed the GitHub Marketplace UI shows prereleases, but the button "use latest version" does download v2.0 although the list dropdown next to it shows all available releases!

I've deleted the `v0.2.1-beta` release and tag for now until we sort out the issue.

**Comment by nonproto** [comment]
Just wanted to throw my repo in with the same issue.
The action setup
```
      - name: Delete any draft releases and last latest tag
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
The action output
```bash
📕  given repo is "CarlosEsco/Neko"
🏷  given tag is "latest"
🍻  found [29](https://github.com/CarlosEsco/Neko/actions/runs/3676154048/jobs/6216448030#step:12:29) releases to delete
👍🏼  all releases deleted successfully!
🌶  failed to delete ref "refs/tags/latest" <- Reference does not exist
😕  Proceeding anyway, because tag not existing is the goal
```

There must have been some limit on the lookup for deletion, because it didn't delete all my releases just the last 6 months.
