### ISSUE TITLE
Node.js 12 actions are deprecated - v0.2.0.

### ISSUE THREAD

**Issue by MarcinWojtasEit** [dev-drprasad/delete-tag-and-release#18]
Warning message during execution:
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: **dev-drprasad/delete-tag-and-release@v0.2.0**. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Please create a new release that contains this fix:
https://github.com/dev-drprasad/delete-tag-and-release/issues/12

**Comment by thadguidry** [comment]
Can you give me the steps you used to reproduce the warning message about Node.js 12 ?
It's possible your GitHub Runner or local Runner does not have Node16 available?  This depends on the image you are using for the Runner. So double check that.

**Comment by MarcinWojtasEit** [comment]
@thadguidry yes of course

      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: v${{ matrix.tag }}
          delete_release: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE }}

**Comment by MarcinWojtasEit** [comment]
@thadguidry 


```
  tag:
    runs-on: ubuntu-latest
    needs: [release-please, build]
    strategy:
      matrix:
        tag: ['${{ needs.release-please.outputs.major }}.LATEST','${{ needs.release-please.outputs.major }}.RELEASE', '${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.RELEASE']
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: v${{ matrix.tag }}
          delete_release: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE }}
```

**Comment by MarcinWojtasEit** [comment]
@thadguidry as you can see I use "runs-on: ubuntu-latest"

**Comment by thadguidry** [comment]
I cannot reproduce this.  Can you provide the link to your Actions log where this error occurred in your repo if it's public?

**Comment by MarcinWojtasEit** [comment]
@thadguidry, weird, the repository isn't public but I can send you the workflow definition

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/13188419/225855058-129f35d8-6397-4996-b0f1-2e72d92c49c7.png">

**Comment by MarcinWojtasEit** [comment]
```
name: test
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          token: ${{ secrets.RELEASE_PLEASE }}
    outputs:
      major: ${{ steps.release-please.outputs.major }}
      minor: ${{ steps.release-please.outputs.minor }}
      patch: ${{ steps.release-please.outputs.patch }}
  build:
    if: contains(github.event.head_commit.message, 'MarcinWojtasEit/release-please')
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: cardinalby/git-get-release-action@v1
        id: git-get-release-action
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE }}
        with:
          tag: v${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
      - name: Add description to Release
        uses: irongut/EditRelease@v1.2.0
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
          id: ${{ steps.git-get-release-action.outputs.id }}
          body: |
            ### Link to the artifact:
            * https://github.com/MarcinWojtasEit/playground
  tag:
    if: contains(github.event.head_commit.message, 'MarcinWojtasEit/release-please')
    runs-on: ubuntu-latest
    needs: [release-please, build]
    strategy:
      matrix:
        tag: ['${{ needs.release-please.outputs.major }}.LATEST','${{ needs.release-please.outputs.major }}.RELEASE', '${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.RELEASE']
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: v${{ matrix.tag }}
          delete_release: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE }}
      - name: Create tag
        id: create-tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{ matrix.tag }}
          github_token: ${{ secrets.RELEASE_PLEASE }}
```

**Comment by thadguidry** [comment]
You can see that we have the Action already using Node16 here https://github.com/dev-drprasad/delete-tag-and-release/blob/master/action.yml  So not sure what's happening on your end, or your Runner environment?

But I think possibly found an issue and fixed it.
Can you try again?
Also would be curious to know if it works with `@master` instead of `@v0.2.0` ?
or now that I've patched the package version, perhaps it works with either annotation now?

**Comment by thadguidry** [comment]
@MarcinWojtasEit also depending on your exact needs.  You might find[ this action](https://github.com/marvinpinto/action-automatic-releases) is even more suited to what you need.  I've heard from others that basically liked the way this action worked for them, if they just wanted to always push a `latest` and remove any previous associated releases:

```yaml
- uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            ./zip/game.zip
            image*.img
```
