### ISSUE TITLE
Infinite worlflow run loop 

### ISSUE THREAD

**Issue by vitoo** [dev-drprasad/delete-tag-and-release#38]
Hello,

by doing a delete and create release, i got a weird behavior, an infinite workflow run happened, do you know why ?

The 2 steps : 

```yaml
      - name: Delete previous release
        uses: dev-drprasad/delete-tag-and-release@v1.0 
        with:
          tag_name: ${{ github.ref_name }}  
          github_token: ${{ secrets.token }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: weytop-webrtc-tester.deb
          tag_name: ${{ github.ref_name }} 
          name: Release ${{ github.ref_name }}
          draft: false 
          token: ${{ secrets.token }}
          target_commitish: ${{ github.ref_name }}     
```

During all night it created 1 workflow run per minute, and for a push event, but i pushed only one time   : 

![image](https://github.com/dev-drprasad/delete-tag-and-release/assets/995694/92bb690f-67f0-4254-b38b-beeea075e842)
