### ISSUE TITLE
Obsolete action?

### ISSUE THREAD

**Issue by Thijss** [dev-drprasad/delete-tag-and-release#39]
Hi,

I don't want to discredit anyone's work/effort, but nowadays the github CLI provides an easy way to delete releases.
Therefore, I think this action could be archived/removed since it doesn't add any value anymore.

example with gh cli:

```yaml
    - uses: actions/checkout@v3
    - name: Delete Release
      run: gh release delete ${{ github.event.inputs.tag }} --cleanup-tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by ghost** [comment]
Note that the github CLI is only preinstalled on GitHub-hosted runners.
> GitHub CLI is preinstalled on all GitHub-hosted runners. For each step that uses GitHub CLI, you must set an environment variable called GH_TOKEN to a token with the required scopes. 
(link: https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows)

On self-hosted runners it would be:

``` yaml
  - uses: actions/checkout@v3
  
  # needed only on self-hosted runners, on github cloud runners it's already pre-installed
  - name: Install GitHub CLI
    run: |
      type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
      && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
      && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
      && sudo apt update \
      && sudo apt install gh -y
    
  - name: Delete Release
    run: gh release delete ${{ github.event.inputs.tag }} --cleanup-tag
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

see also https://github.com/cli/cli/blob/trunk/docs/install_linux.md

**Comment by jneilliii** [comment]
what about failing silently? if using this approach their is a non 0 return code from the command if the release doesn't exist.

**Comment by Kylmakalle** [comment]
> what about failing silently?

Not so silent, but simple. To fail silent, redirect stdout/stderr to `/dev/null`
```shell
gh release delete ${{ github.event.inputs.tag }} --cleanup-tag || true
```

**Comment by ghost** [comment]
> what about failing silently? if using this approach their is a non 0 return code from the command if the release doesn't exist.

Just set `continue-on-error` to true 😄 

[docs for continue-on-error](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error)

``` yaml
  - name: Delete Release
    run: gh release delete ${{ github.event.inputs.tag }} --cleanup-tag
    continue-on-error: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
